# WARNING: This is currently outdated- please use singularity definition file instead.
FROM ubuntu:17.10
COPY ./install.sh ./
RUN chmod +x ./install.sh && ./install.sh
ENTRYPOINT ["gramtools"]
CMD []
